---
- name: Provision
  hosts: "all"
  gather_facts: yes
  vars_files:
    - vars/vars.yml
  roles:
    - init
    - zerotier
    - docker
    - role: timecapsule
      ansible_user: "{{ user.name }}"
    - role: transmission
      ansible_user: "{{ user.name }}"
    - role: plex
      ansible_user: "{{ user.name }}"
    - role: postgres
      ansible_user: "{{ user.name }}"
    - role: minio
      ansible_user: "{{ user.name }}"
    - role: pi-hole
      ansible_user: "{{ user.name }}"
