---
- name: Setup smb folders
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
    owner: "{{ user.name }}"
  loop:
    - "{{ folder.config }}/timecapsule/users"
    - "{{ folder.data }}/files"
    - "{{ folder.data }}/timemachine"
    - "{{ folder.data }}/timemachine2"

- name: Copy config files
  copy:
    src: ../conf/users
    dest: "{{ folder.config }}/timecapsule"

- name: Start timecapsule service
  docker_compose:
    project_name: timecapsule
    definition:
      version: "3.7"
      services:
        timecapsule:
          network_mode: "host"
          environment:
            - EXTERNAL_CONF=/users
            - CUSTOM_SMB_CONF=false
            - CUSTOM_USER=false
            - DEBUG_LEVEL=1
            - HIDE_SHARES=no
            - MIMIC_MODEL=TimeCapsule8,119
            - SET_PERMISSIONS=false
            - SMB_INHERIT_PERMISSIONS=no
            - SMB_NFS_ACES=yes
            - SMB_METADATA=stream
            - SMB_PORT=445
            - SMB_VFS_OBJECTS=acl_xattr fruit streams_xattr
          restart: unless-stopped
          volumes:
            - "{{ folder.config }}/timecapsule/users:/users"
            - "{{ folder.data }}/files:/opt/files"
            - "{{ folder.data }}/timemachine:/opt/timemachine"
            - "{{ folder.data }}/timemachine2:/opt/timemachine2"
            - /var/lib/samba:/var/lib/samba
            - /var/cache/samba:/var/cache/samba
            - /run/samba:/run/samba
          ulimits:
            nofile:
              soft: 65536
              hard: 65536
          container_name: timecapsule
          image: mbentley/timemachine:smb
          logging: &default_logging
            driver: json-file
            options:
              max-size: "1m"
              max-file: "5"

