---
- name: Run Postgres server
  docker_compose:
    project_name: postgres
    definition:
      version: '3.1'
      services:
        db:
          image: postgres
          restart: always
          environment:
            POSTGRES_PASSWORD: "{{ postgres.pwd }}"
          ports:
            - "5432:5432"
          logging: &default_logging
            driver: json-file
            options:
              max-size: "1m"
              max-file: "5"
        adminer:
          image: adminer
          restart: always
          ports:
            - 8080:8080
